name: Trigger PR
on:
  pull_request:

jobs:
  milestone:
    name: Add Milestone
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
      with:
        submodules: true

    - run: npm ci
      working-directory: ./actions-milestone
    - run: npm run build
      working-directory: ./actions-milestone
    - uses: ./actions-milestone
      with: 
        repo-token: "${{ secrets.GITHUB_TOKEN }}"
        configuration-path: .github/milestone.yml@master
        configuration-repo: iyu/actions-milestone
